/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 2118672e85a5a9b3dc89d6bbc3b77f24)
// Runtime types generated with workerd@1.20260722.1 2026-7-27 nodejs_compat
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}

// Begin runtime types
